### ISSUE TITLE
adapt the banner to the mobile version

### ISSUE THREAD

**Issue by IvanProgrammer1703** [school-spring-2019/be-latte#34]

**Comment by IvanProgrammer1703** [comment]
will be replaced by a photo of the banner when you change the permissions to mobile

**Comment by BOMBO454** [comment]
##Задача сделать норм баннер
1. Устранить выпадание за пределы страницы блака с текстом
![image](https://user-images.githubusercontent.com/20165225/53164670-2fad0b80-35ea-11e9-9e18-0c6998db6ae5.png)
2. Сделать шрифт побольше. Текст баннера очень важен

**Comment by IvanProgrammer1703** [comment]
Начал разбираться оказалось текст был завернут в блок с классом стилей которого не существует, класс прописан, а в style его нету. Мой косяк((
