### ISSUE TITLE
 Reduce the top indent in the mobile version

### ISSUE THREAD

**Issue by Androooooooid** [school-spring-2019/be-latte#41]
Сделаем поменьше отступ у меню в мобильной версии

**Comment by Androooooooid** [comment]
margin-bottom:250px; между блоками меню сделаем меньше margin-bottom:0px отступ будет выглядеть лучше.

**Comment by BOMBO454** [comment]
Да. Норм. Надеюсь бородач не будет это всё читать
Вот ещё список для видимости

1. первый
2. второй
3. третий

а тут код будет 
```
display:none;!important;
```
